# -----------------------------------------------------------------------------
# IoTGuard Configuration
#
# Purpose
#   - Declare the feature list used by training/inference and the decision
#     policy parameters consumed by the decision loop and dashboard.
#
# Notes
#   - Training reads this feature order (scripts/train_supervised.py).
#   - Decision loop hot-reloads values under `decision` at runtime.
# -----------------------------------------------------------------------------
features:
  - flows
  - bytes_total
  - pkts_total
  - uniq_src
  - uniq_dst
  - syn_ratio
  - mean_bytes_flow

lgbm:
  n_estimators: 250
  num_leaves: 64
  learning_rate: 0.05
  subsample: 0.8
  colsample_bytree: 0.8
  
decision:
  threshold: 0.70
  grace: 2
  window: 5
  cooldown_sec: 5
  instant_block: 0.95

  # set to false to actually block
  dry_run: true

  # choose one:
  hook: windows         # or: linux
  windows_hook: scripts/block_ip.ps1
  linux_hook: scripts/block_ip.sh




